### PR TITLE
make travis, updating gocc

### PR DESCRIPTION
**Pull request by deosjr**
As per https://github.com/awalterschulze/gominikanren/pull/19#issuecomment-1102700839

### CODE REVIEW

**Comment by deosjr** [comment]
Perhaps I misunderstand, but seems to me that running `git diff --exit-code .` in `make travis` will throw an error on any changes ever? That doesn't seem helpful.

**Comment by awalterschulze** [comment]
The idea is that all generated code is checked in

I wonder if make travis uses the locked versions? Or simply the newest
code. Maybe it is possible to make it use the locked versions?

**Comment by deosjr** [comment]
go get doesnt reinstall, so I was running an old version of gocc locally ;) fixed

**Comment by awalterschulze** [comment]
Maybe we could rename `travis` to `ci` or something more generic in the Makefile, but we could do that in a follow up diff.  Thanks for fixing this it looks great :D

**Review by awalterschulze — APPROVED** [review]

**Pull request merged**
